language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - pypy
# command to run tests
script:
 - python -c "import sys; sys.stderr.write(sys.version)"
 - python -c "import sys; '%x' % sys.maxsize, sys.maxsize > 2**32"
 - python setup.py test
 - python setup.py ptr
 - python ez_setup.py --version 3.5.1
